### ISSUE TITLE
How do I create a custom checkout payment?

### ISSUE THREAD

**Issue by dungahk** [mercadopago/px-android#1270]
A long time ago, I was able to start a basic activity that would just get the Card details and then send the information to my backend and in there I would do all the work, but with this new version I can't seem to find a documentation on how to do that.

I would use the following code:
`new MercadoPago.StartActivityBuilder().setActivity(activity).setPublicKey(PUBLIC_KEY_SELLER.getValue()).startCardVaultActivity();`

**Comment by zehemz** [comment]
Hi There @dungahk ,
There is a way to do something similar to that. You have to first exclude all but cards payment types in the preference.

Second, you must configura a [PaymentConfiguration](https://github.com/mercadopago/px-android/blob/506e28f252731859f1b898e13e63fd9b0a948bd1/px-checkout/src/main/java/com/mercadopago/android/px/core/MercadoPagoCheckout.java#L179) and set your own [payment processor](https://github.com/mercadopago/px-android/blob/506e28f252731859f1b898e13e63fd9b0a948bd1/px-checkout/src/main/java/com/mercadopago/android/px/core/PaymentProcessor.java).
Insted of makeing the payment by our own when the user make the payment confirmation, it allows you to generate your payment and notify us to show success or fail messages.

PX V4 is about hole payment experience and not just a Card input.

Hope it helps.
