### ISSUE TITLE
Que clase reemplaza la funcionalidad de MerchantServer?

### ISSUE THREAD

**Issue by gregoriomartin** [mercadopago/px-android#1296]
En el SDK viejo usaba MerchantServer para llamar a un método post de nuestra capa de servicios y obtener el CheckoutPreference.

Según la documentación en el último SDK se llama CustomServer la reemplazante, pero no existe tal clase.

Intenté crear mi propia forma de obtener el CheckoutPreference pero este tiene constructor privado.

**Comment by zehemz** [comment]
Hola!
MerchantServer no existe más en V4, directamente podes hacerle una pegada a la api de preferencias con tu propio rest client o mediante tu server para generar un id.
La documentación de la api de preferencias la podes encontrar en developers.mercadopago.com
