### ISSUE TITLE
Boleto Bancário payment not working for Brazil.

### ISSUE THREAD

**Issue by imjaspreet** [mercadopago/px-android#1370]
I am integrating the SDK for android for brazil. Credit cards payments are working fine but when i try with Boleto Bancário payment then It is throwing an error 

**ERROR**
ApiException{cause=[Cause{code='7521', description='To generate a registered boleto the following parameters are required: payer.address.zip_code , payer.address.street_name , payer.address.street_number , payer.address.neighborhood , payer.address.city , payer.address.federal_unit'}], error='bad_request', message='To generate a registered boleto the following parameters are required: payer.address.zip_code , payer.address.street_name , payer.address.street_number , payer.address.neighborhood , payer.address.city , payer.address.federal_unit', status=400}

**But I am sending all details in Body for creating preference ID:**
**Body:**
{
	"items": [
        {
            "title": "Test",
            "quantity": 1,
            "currency_id": "BRL",
            "unit_price": 10
        }
    ],
    "payer": {
    	"email": "test@gmail.com",
    	"address": {
    		"street_number": 259,
    		"street_name":"Av. Beira Mar",
    		"zip_code":"40420340",
    		"city":"Salvador",
    		"federal_unit":"BA",
    		"neighborhood":"Ribeira"
    	}
    }
}    

Any help will be appreciated
Thanks.

**Comment by zehemz** [comment]
Hi there @imjaspreet ,
Which version of our lib are you using?

**Comment by zehemz** [comment]
Hi there, this is the minimum amount of data to post a payment needed by mercadopago. 
Anyway, if you can provide us which version are you using and if it's just a post or the complete checkout flow will be great.
```
"payer": {
"first_name": "Test",
"last_name": "Test",
"identification": {
          "type": "CPF",
          "number": "XXX333333"
      }
}
```

**Comment by zehemz** [comment]
Please, if you still having issues please provide us more info. We will close this issue by the time being.
