### ISSUE TITLE
Icon in "Recent apps" is replaced by the default Android icon

### ISSUE THREAD

**Issue by RamonJSanchez** [mercadopago/px-android#1384]
When the library is added to the project (implementation 'com.mercadopago.android.px:checkout:4.3.0') the app's icon displayed in the recent app's menu is replaced by the default android icon.
If I remove the library the app's icon is displayed correctly.
I suppose that the library contains the default icon in the resources (and it shouldn't).

**Comment by zehemz** [comment]
Hi, it doesn't.
https://github.com/mercadopago/px-android/blob/master/px-checkout/src/main/AndroidManifest.xml

Anyway, the right thing to do is to override the icon image in your app manifest.
