### ISSUE TITLE
Difference between px-android and sdlk-android

### ISSUE THREAD

**Issue by sebasira** [mercadopago/px-android#140]
Hi! I'm trying to develop an app using MercadoPago with basic check out, I've been trying with sdk-android (with no luck by the way). Now, I've found these repo. Which one should I use?

The problem I'm facing with sdk-android is that I don't know how to identify the merchant using CLIENT_ID and CLIENT_SECRET instead of MERCHAT_PUBLIC_KEY, here's the issue I've opened about it: [sdk-andorid issue](https://github.com/mercadopago/sdk-android/issues/20).

Thank you very much for your time

**Comment by mreverter** [comment]
Hi! You can take a look at our documentation:
[MercadoPago Android SDK V2 Docs](http://mercadopago.github.io/px-android/)
