### ISSUE TITLE
tienem que crear una version mas pequena

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1441]
Es increible que una API para cargar pagos tenga 5.0MB... com certeza hay mucha basura e codigo recursos desnecesarios en esto

La api de google billing no tiene ni 1MB... 
mi app entero tiene ahora 4.4MB

es demasiado malo un desarollo que incluye doble tamano del app solo para una cosa simples que es acessar la api de pagos

**Comment by zehemz** [comment]
Si tu app se splitea por arquitectura la lib pesa menos de 2 MB.
Por otro lado, el peso de la lib se debe a los native .o de fresco para soporte de imagenes webp con transparencia que no están soportados por api <18. (Nuestra lib soporta desde api 16). Si usted es usuario de fresco o planea usar fresco como lib de carga de imágenes este es un costo de peso hundido.

Lo invitamos @bolds07 a que haga los aportes que consideres para mejorar la calidad en el peso del módulo. Nuestras dependencias tratamos de mantenerlas al mínimo y achicar el codebase.

Gracias.

**Comment by bolds07** [comment]
Eso no es bien verdad

https://ibb.co/fp6xHzk

Como puede mirar por la imagen mas de 2MB en tu api es solo imagenes... se que les gusta mostrar al usuario una linda foto de la targeta visa que el tiene en su billetera... pero eso es inutil y creo que solo el proprio designer mira ese tipo de detalle

La suerte de vosotros es que paypal, google pay, stripe y los grandes gateways de pagamento en el mundo tiene una participacion miserable en sudamerica 

La api de google billing tiene menos de 100kb y el usuario puede pagar en 3 segundo usando su huella paypal tiene 500kb

Asi que suerte al equipo de desarrollo por tener un jefe que no conoce (o no sabe comparar) el servicio de los concorrientes (y espo porque ni hablamos de la qualidad de codigo)

besitos

**Comment by zehemz** [comment]
@bolds07  2 cosas que he notado:
La primera, corriendo nuestro sample en release no notamos el tamaño de 2 megas que menciona.
<img width="437" alt="captura de pantalla 2018-12-11 a la s 14 31 48" src="https://user-images.githubusercontent.com/7827612/49818487-9cd23400-fd51-11e8-8fe6-71141dddbf47.png">

Por otro lado, puede splitear el apk por densidad el tamaño se reduce a 400k aprox en el peor de los casos (xxxhdpi).
Realmente nos encantaría poder estar a la altura de tus expectativas, sin embargo nuestro grupo es reducido y no contamos con tanto tiempo de desarollo como google billing.

Te invitamos a colaborar con alternativas y generar un sistema de recursos a demanda para reducir el tramaño de nuestra lib.
