### ISSUE TITLE
[QUESTION] reuse preference id

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1446]
Is there any way to i tell the api to reuse a past preference id? 

Lets say for example my user puts an item in the basket, then press the button buy... 10 times can i tell the api to "reuse" the previous preference id (since is same user, same item) or i do need to handle this in my app logic to avoid stay with a thousand pending orders from the same user?

if i do, is there any consequence if i let user gets a thousand pending orders?

**Comment by zehemz** [comment]
Hi @bolds07 you don't need an order to place a payment. You can just pay the same preference any times you want.
Take care about the expiration date of the preference. You can create and modify the preference once created.
Please, check this page https://www.mercadopago.com/developers/ and if you need more info please use the contact form.

Regards.
