### ISSUE TITLE
mixed language in user checkout

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1447]
This is a pretty obvious problem, but you api isn't well translated to all languages it support (or should)

https://ibb.co/NxBd48j

I'm trying to make a payment in BRL, but my phone lanaguage is english... pay attention to the completitude of your strings.xml... i think android studio warn about that

**Comment by zehemz** [comment]
@bolds07 the translations of payment methods come from backend, does not exists in the application. Anyway thank you for the report, we will fix it in our backend.
