### ISSUE TITLE
not receiving ipn notifications when android checkout

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1448]
I'm creating the preferencies for test in my node js server.

after creating the preference if i use the sanbox url to pay with test credit card in my browser, everything goes fine

if i get the same preference id and try to pay on android with 
`new MercadoPagoCheckout.Builder("TEST-blabla", (String) object.get("preferenceId")).build().startPayment(TestActivity.this, 789);`

the payment flow goes fine, i the client gets OK in the smartphone, but my backeend doesn't get the IPN notifications

**Comment by zehemz** [comment]
@bolds07  please, for any API issue please check the contact form in our developers site.
IPN notifications is not part of this project scope.

Thanks.
