### ISSUE TITLE
Type mismatch: inferred type is CardToken but SavedESCCardToken! was expected

### ISSUE THREAD

**Issue by filipepatricio** [mercadopago/px-android#1556]
After Updating to version 4.6.1 

This Kotlin compiler error started to appear:
`Type mismatch: inferred type is CardToken but SavedESCCardToken! was expected`

I was calling this `MercadoPagoServices.java` method: `public void createToken(final CardToken cardToken, final Callback<Token> callback)` on a Kotlin file/class
 
To "fix it" I had to rollback to 4.5.2

**Comment by zehemz** [comment]
We had a mistake in our public api, we will rollback it in the next version 4.6.2
