### ISSUE TITLE
El email es requerido

### ISSUE THREAD

**Issue by jdnichollsc** [mercadopago/px-android#1603]
Hi guys,
I have this issue testing the basic example of the documentation 
![screenshot_20190305-003712_example](https://user-images.githubusercontent.com/2154886/53787217-15c5cf80-3eec-11e9-94bd-fd06c83d7f74.jpg)
Any help is really appreciated!

**Comment by matiasromar** [comment]
Hi @jdnichollsc, 
The payer's email is required. You must set it in your CheckoutPreference.
You can find more information in our documentation [here](https://github.com/mercadopago/px-android/blob/master/README.md).

Regards
