### ISSUE TITLE
App crash Invoke-customs are only supported starting with Android O

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1610]
I was told to use version 4.7.2

```
 @zehemz Collaborator zehemz commented 23 hours ago • 
@bolds07 this issue has been fixed on 4.6.2
4.6.1...4.6.2
Anyway, we recommend you to use 4.7.2 that is a newer version.
Soon in 4.8.0 we will reduce the size of our pngs one of the things you ask for.

```

But setting the api version i get this error on compile

> App crash Invoke-customs are only supported starting with Android O

Android studio simple doesn't compile the project anymore by changing mercadopago api version

Stackoverflow people told to add

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
and i did but still doesn't work

**Comment by zehemz** [comment]
You must use to support android java8 features builtools 3.3.+ and gradle wrapper version 4.10.2.
also, put those compile options in your application file.

This give you a lot of benefits in your project. AAPT2 (resource shrinking and code optimizations), java8 default interface methods, lambdas and method references.

If you have conflicts with that you can just use 4.6.2 version that has that fix already without java8 support.

**Comment by bolds07** [comment]
Do you use any java 8 features in this api? i didn't see any lamba expression in the code or method reference....

there isn't any reason to use java 8 in this project!!! once more you are just updating something without knowing what you are doing just because someone told you to do so...

who is the chief archtect of this company? this guy must go back to school urgent.... looks like you develop a system like a supplier selling shit in power point... with fancy animations and big letters to imprese people who doesn't understand a letter of technology

is going to take a week of work to migrate but im really giving up of this api

so far i believe im only of the few users of it

**Comment by zehemz** [comment]
@bolds07 you should be more respectful with us. If you keep being aggressive nothing positive will happen.

Yes, we use java 8 default interface feature to avoid making breaking changes on some of our api's.
It allow us to support new features without the need to modify each integration.

Responding to:

> is going to take a week of work to migrate but im really giving up of this api

We made the change in one of our apps and it was less than 5 minutes, shouldn't take a week at all. Anyway, again, you can use 4.6.2 that does not need this change in your compile options.

**Comment by zehemz** [comment]
@bolds07 by the way, android is moving to support 1.8 by default, so maybe you should consider reading what I sent you about R8 and D8.

**Comment by bolds07** [comment]
> @bolds07 you should be more respectful with us. If you keep being aggressive nothing positive will happen.

I'm not patient, I myself design, develop, sell and provide costumer service to my app... i've over 3k daily users and around 30k monthly users

Is not exactly relaxing when i see that the most frequent crashes or bugs in my app come from third party api that just deals with one single feature... 
And i'm not even talking about the gateway logic itself... i've dozens of complaints about people saying their orders weren't accepted even if they have a valid credit card

so i mysefl feel the right to be stressed when come here...

Make a survey... ask the devs how are they using your api, which kind of business they deal with or how many users they have...

I might just be a crazy guy yelling out loud... or a might be the voice to be listen
