### ISSUE TITLE
Color customization programmatically

### ISSUE THREAD

**Issue by jdnichollsc** [mercadopago/px-android#1613]
Hi guys,

Is it possible to change colors at runtime?

Thanks in advance,
Juan

**Comment by zehemz** [comment]
Hi @jdnichollsc, officially we do not allow to change colors at runtime, but you can override our colors in your app xml statically.

If you tell us what's your use case we may consider adding the feature.

**Comment by jdnichollsc** [comment]
@zehemz it would be very useful to improve the experience, to customize the styles per user

**Comment by zehemz** [comment]
@jdnichollsc Sorry, at the moment we won't put it on roadmap. Anyway if you want to fork or contribute we will evaluate the change.

Thanks.
