### ISSUE TITLE
Error with marketplace functionality using mobile SDK (android and IOS).

### ISSUE THREAD

**Issue by castedm** [mercadopago/px-android#1671]
Creando preferencias en el servidor (back-end) y enviandolas a la aplicación mobile para que realice el check-out de la siguiente manera:

MercadoPagoCheckout
                .Builder(publicKey, checkoutPreferenceId)
                .build()
                .startPayment(view.activity!!, OrderValidationActivity.MP_CHECKOUT_REQUEST_CODE)
    }
Parámetros: 
He probado con 
    **CASO1**    publicKey  -->  Public Key del marketplace.
    **CASO2**    Public Key que retorna la vinculación del vendedor
   checkoutPreferenceId --> preferenceId que se obtuvo en el servidor con los datos del cliente, el acceskey del vendedor y los datos del producto.

En el **CASO1** el SDK muestra un error en pantalla (no retorna error capturable por código) el error es: (¡Uy! Algo salió mal vamos a solucionarlo. Intenta más tarde.)

En el **CASO2**  se logra capturar el pago, pero la venta se asigna al marketplace y no al vendedor, siendo que incluso se está pasando el PublicKey del vendedor.

Según el soporte de mercado pago: "Tr informamos que hemos analizado el codigo de la sdk mobile y las mismas no soportan la modalidad market place."  

Yo entiendo que es un error, dado que no está documentado que no se pueda usar el marketplace de esta manera.

**Comment by zehemz** [comment]
Hola! lamentablemente de momento no tenemos soporte a marketplace. Próximamente podremos brindarlo pero de momento no es factible en mobile.

Lamentablemente la preferencia posee algunos parámetros (como marketplace y shipping) que no son features soportados nativamente.

Si nos brindas un poco de info de integración/ para que necesitan el marketplace podemos revisar ponerlo en roadmap.

Gracias.

**Comment by castedm** [comment]
Hola Lucas, 
Te cuento un poco, tenemos una app de comidas, similar a un pedido ya, la cual funciona como un marketplace donde los restaurantes exponen sus productos, cuando el usuario realiza una compra, el pago va directamente al restaurante usando la funcionalidad de mpconnect. 

Para eso necesitamos que el checkout de MP en la app admita la funcionalidad de marketplace. Yo desconozco si existe otro camino diferente para implementar esta funcionalidad, la cual no involucre el SDK de (android & IOS).
Gracias

**Comment by agustinallera** [comment]
Nosotrs estamos teniendo el mismo problema

**Comment by zehemz** [comment]
Hola! vamos a estar analizando el tema para poder darles una fecha de implementación de dicha funcionalidad. Gracias

**Comment by ManuLpz4** [comment]
Aprovechando la consulta. Hay manera de incluir pagos con QR y Marketplace a la vez? O sí o sí el pago por QR es desde la aplicación oficial? Muchas gracias

**Comment by zehemz** [comment]
@ManuLpz4 estamos analizando la posibilidad de hacer una biblioteca de pagos QR, de momento es solo funcionalidad de MercadoLibre pero facilmente implementable con este proyecto.

**Comment by ManuLpz4** [comment]
¿Fácilmente implementable en caso de que la creen o entendí mal? Porque venía desarrollando una aplicación y como que se me quemaron los papeles. Tampoco te quiero andar molestando sinceramente, pero es algo que me interesa mucho. Muchas gracias por tomarte el tiempo de contestarme :)

**Comment by zehemz** [comment]
@ManuLpz4 Es fácil una app q escanee qr y genere preferencias de pago, hay muchas libs open source que leen QRS y el contenido de QR lo podes relacionar con una preferencia de pago desde algún backend tuyo asociando ese contenido a la preferencia. El unico detalle es que hay una normativa para el formato de QR (al menos en argentina).
De todas formas si te interesa tener pagos con QR en tu comercio Instore es un producto que ofrece mercadopago y hasta te pon en en el mapa de las apps de ML y MP.

**Comment by ManuLpz4** [comment]
Gracias por tu respuesta. Si bien lo que me comentás es una parte de mi aplicación, en realidad lo que necesito y no encuentro la manera es escanear el código QR de MercadoPago y poder pagarlo desde mi aplicación

**Comment by zehemz** [comment]
@fnazrala te va a poder decir si es posible @ManuLpz4

**Comment by fnazrala** [comment]
@zehemz @ManuLpz4 Por ahora no es posible para terceros leer los códigos QRs de MercadoPago y pagarlos con el SDK. Como dice Lucas esto se debería poder hacer con una biblioteca de Pegos con QR.
También como te comentaba, los códigos QR para pago en Argentina están normados por el BCRA, y contienen información del vendedor, precisamente para permitir inter operabilidad entre las distintas wallets. Podes hacer uso de eso.

**Comment by ManuLpz4** [comment]
Uh, se me fue la aplicación a la basura. Qué lástima, pero de todas formas muchísimas gracias por contestarme todas las dudas, de verdad :) Un saludo. Y en cuanto pueda pagar QR de MP sin la aplicación oficial ahí estaré jaja

**Comment by zehemz** [comment]
@castedm la versión 4.17 debería tener solucionado el inconveniente de marketplace. Pueden verificarlo? gracias.

**Comment by hostelix** [comment]
Hola un saludo, quería saber si el soporte al marketplace esta disponible, estoy realizando unas pruebas pero el dinero no llega al marketplace si no al vendedor!
