### ISSUE TITLE
Opciones de pago - Colombia

### ISSUE THREAD

**Issue by juandiago** [mercadopago/px-android#1702]
Hola, estoy en medio de un proyecto de desarrollo con Flutter y encontre su libreria, hasta ahora la implementacion haciendo uso de los canales nativos desde Flutter ha sido **genial**.

Solo tengo un problema, cuando ingreso a pagar una referencia desde la app movil, solo me da la opcion de pagar con tarjeta de credito, aunque en la version web tengo disponible todas las opciones de pago para Colombia(ver link). Pq se presenta esta situacion?? 

![Screen Shot 2019-05-10 at 11 55 04 AM](https://user-images.githubusercontent.com/10090040/57543959-8d184500-731b-11e9-8409-03e43cec1e5a.png)

![Screen Shot 2019-05-10 at 11 55 11 AM](https://user-images.githubusercontent.com/10090040/57543969-930e2600-731b-11e9-84ee-98d650c56793.png)

**Comment by zehemz** [comment]
Hola! lamento comentarte que de momento solo tarjeta de credito es el medio disponible en colombia.

Voy a averiguar si esta en roadmap modificar esto próximamente.

Saludos!

**Comment by juandiago** [comment]
Entiendo, si puedes compartirme alguna info acerca de la probabilidad de que lo incluyan en su roadmap les estare agradecido.
