### ISSUE TITLE
GuessingCardActivity shows only portrait (no landscape)

### ISSUE THREAD

**Issue by fermartinez1** [mercadopago/px-android#1784]
Hay algún motivo por el cual GuessingCardActivity esta en el manifest de la siguiente manera?

` <activity
            android:name=".internal.features.guessing_card.GuessingCardActivity"
            android:screenOrientation="sensorPortrait"
            android:theme="@style/Theme.MercadoPagoTheme.NoActionBar"
            android:windowSoftInputMode="adjustResize"/>`

con el screenOrientation el activity no rota a landscape.

Gracias.

**Comment by zehemz** [comment]
@fermartinez1 vamos a modificar la forma en que presntamos esa pantalla pronto. De momento no queremos presentar esta pantalla en landscape de todas formas momentáneamente.

**Comment by fermartinez1** [comment]
Genial, muchas gracias.
