### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.mercadopago.android.px.internal.features.review_and_confirm.ReviewAndConfirm$View.

### ISSUE THREAD

**Issue by christiansalazar** [mercadopago/px-android#1803]
similar to issue https://github.com/mercadopago/px-android/issues/1549

app crash when operation is cancelled (click on red icon after payment is aborted by the platform, aborted due to testing card)

**gradle config:** 
implementation 'com.mercadopago.android.px:checkout:4.0.+'

**i bypass this problem by using:**
implementation 'com.mercadopago.android.px:checkout:4.5.2'

**Comment by zehemz** [comment]
@christiansalazar it's already fixed you should not reopen this issue in this case.
Thanks anyway.
