### ISSUE TITLE
Pay Error - Payer equals Collector 

### ISSUE THREAD

**Issue by jlmacedo** [mercadopago/px-android#1808]
When click on "Pay" button show up a message "Payer equals Collector", I already changed payer email and is displayed the same error message.

Using test credentials and Version 4.16.+

**Comment by zehemz** [comment]
You must follow the instructions in the readme to create each preference.

The preferences is created with the seller access token (preference owner) and can't be the same as the payer user.

Please if you still having issues please send us your public key and preference id to review it.

**Comment by jlmacedo** [comment]
@zehemz I alread did this, but the problem continues. 

I using test credentials and other email to test it.

Public: TEST-c2d43e72-2815-4957-b221-89a455c448d1
Preference: 334058375-89ea3f66-610e-4800-b6ca-ea9e816e8e0c

**Comment by zehemz** [comment]
![Screenshot_1563997321](https://user-images.githubusercontent.com/7827612/61823500-50e08500-ae32-11e9-8794-178000bc6f62.png)

I've done a payment with version 4.17 (master) with no issues.

Please provide us the error body, screenshots step by step (with no card data) and integration info (code).

**Comment by jlmacedo** [comment]
![Screenshot_1563998115](https://user-images.githubusercontent.com/5131329/61824387-3c04f100-ae34-11e9-8f40-ad6dac0ddef3.png)
![Screenshot_1563998179](https://user-images.githubusercontent.com/5131329/61824388-3c04f100-ae34-11e9-9f2b-89ed18f2aefb.png)
![Screenshot_1563998184](https://user-images.githubusercontent.com/5131329/61824390-3c04f100-ae34-11e9-89f9-02de2948d3d4.png)
![Screenshot_1563998188](https://user-images.githubusercontent.com/5131329/61824391-3c04f100-ae34-11e9-8842-6f7788b5005c.png)
![Screenshot_1563998191](https://user-images.githubusercontent.com/5131329/61824392-3c9d8780-ae34-11e9-93b9-e5804905d3d8.png)

`private void getPreferenceID()
    {
        
        String url = "https://api.mercadopago.com/checkout/preferences?access_token=TOKEN";

        final JSONObject jsonBody;
        try
        {
            jsonBody = new JSONObject("{\"items\": [\n" +
                    "               {\n" +
                    "               \"title\": \"Title\",\n" +
                    "               \"description\": \"Description\",\n" +
                    "               \"quantity\": 1,\n" +
                    "               \"currency_id\": \"BRL\",\n" +
                    "               \"unit_price\": 39.90\n" +
                    "               }\n" +
                    "           ],\"payment_methods\":{\"excluded_payment_methods\":[],\"excluded_payment_types\":[{\"id\":\"atm\"},{\"id\":\"debit_card\"},{\"id\":\"ticket\"}]},\"payer\":{\"email\":\"EMAIL\"}}");

            jsonObjectRequest = new JsonObjectRequest
                (Request.Method.POST, url, jsonBody, response ->
                {
                    Log.e("res", response.toString());

                    try
                    {
                        JSONObject jObj = new JSONObject(response.toString());

                        new MercadoPagoCheckout.Builder("PUBLIC", jObj.getString("id"))
                                .setPrivateKey("TOKEN")
                                .build()
                                .startPayment(this, REQUEST_CODE);
                    } catch (JSONException e) {
                        Log.e("ej",e.getMessage());
                        e.printStackTrace();
                    }

                }, error -> {
                    Log.e("error", "Ocorreu um erro.");
                }){
                @Override
                public Map<String, String> getHeaders() {
                    Map<String, String> headers = new HashMap<>();
                    headers.put("Content-Type", "application/json");
                    return headers;
                }
            };
            AppController.getInstance().addToRequestQueue(jsonObjectRequest);
        }
        catch (JSONException e)
        {
            Log.e("ej",e.getMessage());
            // JSON error
            e.printStackTrace();
        }
    }`

**Comment by zehemz** [comment]
You must not send  ```setPrivateKey()``` as a parameter when you are initializing PX.
Access token / private key are **PAYER** keys, not seller's.
that private key is intended to use only if you have access to mercadopago's login access token natively.

**Comment by jlmacedo** [comment]
Now I understand, it's working. Thank you!
