### ISSUE TITLE
 bug starting app

### ISSUE THREAD

**Issue by maycon1038** [mercadopago/px-android#1813]
bug starting app
    java.lang.BootstrapMethodError: Exception from call site #59 bootstrap method

**Comment by frankpc13** [comment]
change the release version in build.gradle to:
`implementation 'com.mercadopago.android.px:checkout:4.0.+'`
Maybe its a bug from the latest release 🤔

**Comment by zehemz** [comment]
hi, try the newest version of PX 4.+ @frankpc13  4.0 version is already too old.
