### ISSUE TITLE
Como asociar una tarjeta al comprador 

### ISSUE THREAD

**Issue by efreibe** [mercadopago/px-android#1848]
Hola, estoy usando la version 4 de la librería, y siguiendo todas las instrucciones del link https://www.mercadopago.com.ar/developers/es/guides/payments/mobile-checkout/receive-payments/ logro hacer un pago utilizando el token sandbox.

El método que uso es exactamente como en el ejemplo:
MercadoPagoCheckout.Builder(publicKey, preferenceId).build()....

Pero cada vez que inicio el flujo vuelve a pedir los datos de la tarjeta, esta genial que el flujo este todo automatizado, pero la respuesta que recibo en onActivityResult no es suficiente, deberia minimamente responder con un credit card token para poder hacer el registro del comprador y asociar la tarjeta.

A todo esto, el objeto que retorna de la activity trae una propiedad card = null.

No veo que haya documentación que explique algo mas que lo que esta en esa pequeña guia de mobile checkout.

Si pueden verificar esto, seria interesante obtener el credit card token para poder asociarlo al cliente y cargar la tarjeta que ya usó anteriormente.

**Comment by guchemeli** [comment]
Hola, entendemos tu pedido pero no está en el roadmap soportar algo así, lo lamentamos mucho.

Saludos
