### ISSUE TITLE
allowBackup impuesto por las libraries

### ISSUE THREAD

**Issue by juandiana** [mercadopago/px-android#1898]
¿Tienen alguna razón por la cual sus libraries declaran que la app debe llevar el atributo `android:allowBackup` en true?

No parece ser una decisión relevante que tome su SDK. Tampoco es algo que sus libraries puedan imponer ya que basta con poner `tools:replace` para sobre escribir este valor.

Se los reporto dado que es molesto tener que andar sobre escribiendo este valor en las apps que deseamos desarrollar con `android:allowBackup` en `false`.

**Comment by guchemeli** [comment]
Tenés razón, lo sacamos, gracias!

**Comment by jotapeg** [comment]
El problema sigue existiendo dado que ahora el manifest merge falla con la library [meliui](https://github.com/mercadolibre/fury_mobile-android-ui/tree/develop/ui) que también impone el `android:allowBackup` en [true](https://github.com/mercadolibre/fury_mobile-android-ui/blob/develop/ui/src/main/AndroidManifest.xml), consumida por ustedes. De todas formas, en caso de corregirse, haría falta pasar a la versión más reciente para tomar el cambio.

**Comment by arcollector** [comment]
Perdon por revivir el thread, pero sigue pasando lo mismo

Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:14:7-34
	is also present at [com.mercadolibre.android:ui:8.8.0] AndroidManifest.xml:10:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.
