### ISSUE TITLE
Error with an android basic checkout

### ISSUE THREAD

**Issue by tes1oner** [mercadopago/px-android#190]
## Hi. I'm trying to use a basic checkout android. Im following this [docs](http://mercadopago.github.io/px-android/index.html)  
**Using the sample code, everything works fine:**  

```
public void submit(View view) {

  // Iniciar el checkout de MercadoPago
  new MercadoPago.StartActivityBuilder()
    .setActivity(this)
    .setPublicKey("TEST-ad365c37-8012-4014-84f5-6c895b3f8e0a")
    .setCheckoutPreferenceId("150216849-ceed1ee4-8ab9-4449-869f-f4a8565d386f")
    .startCheckoutActivity();

}
```

**But if i use my own data for test with a sandbox account, i have an error:** [See video](https://www.youtube.com/watch?v=aVs-EpX0g8s)  
```
new MercadoPago.StartActivityBuilder()
                .setActivity(this)
                .setPublicKey("TEST-fa1b4b03-c885-4c9c-922d-4c2bf7cc2743")
                .setCheckoutPreferenceId(checkoutPreference.getId())
                .startCheckoutActivity();
```  
i'm sure that preference is creating correctly cause if i follow my sandbox_init_point  `"sandbox_init_point": "https://sandbox.mercadopago.com/mlv/checkout/pay?pref_id=149007010-e2c7b039-f0c0-4b35-a1bd-eaaa07f9e53d"`   i have an page for pay.

# I REALLY NEEDS HELP NOW PLEASE :'( :+1:

**Comment by mreverter** [comment]
Hi! Thanks for reporting this issue. There is a problem with our checkout when using test credentials from Venezuela. We're now working to fix it. It should work fine with productive credentials, though.

**Comment by tes1oner** [comment]
@mreverter That's right, that's what I did, set up the actual account and everything went well. What happens if the user trying to pay is not registered in mercadoPago? The pay is procesed ?

**Comment by mreverter** [comment]
@tes1oner yes, the payment is processed.

**Comment by mreverter** [comment]
@tes1oner please, try to use a sandbox credential again, it should work now.
