### ISSUE TITLE
Error en Mobile Checkout - “Algo salio mal ...”

### ISSUE THREAD

**Issue by GFDaniel** [mercadopago/px-android#1909]
En el momento en que inicio “checkout.startPayment” muestra en la pantalla el siguiente mensaje:
                                Algo salio mal… 
               No hay medios de pago disponibles

**Comment by guchemeli** [comment]
Pasanos más información por favor, cómo estás iniciando el checkout puntualmente, con qué configuración

**Comment by GFDaniel** [comment]
De esta manera inicio el checkout:
`int REQUEST_CODE = 1;
MercadoPagoCheckout checkout = new MercadoPagoCheckout.Builder("APP_USR....", checkoutPreferenceId).build();
checkout.startPayment( Activity.this, REQUEST_CODE);`

**Comment by guchemeli** [comment]
Podés pasar la public key con la que estás probando por favor?

**Comment by GFDaniel** [comment]
Esta es: APP_USR-cedd8029-6ab0-4061-9310-147fb2aa1185

**Comment by guchemeli** [comment]
Gracias!
Pudimos comprobar lo que decís, lo pasé para revisar de backend.

**Comment by buttowisk** [comment]
Algum de voces pode me auxiliar na transação? ### **disposto** a pagar

**Comment by GFDaniel** [comment]
@buttowisk te puedo ayudar, escribeme a mi correo daniel.gomez.1213@gmail.com

**Comment by charly0781** [comment]
Hola
Uso la libreria 'com.mercadopago.android.px:checkout:4.44.0'
cuando inicio el .startPayment sale la pantalla
ALgo Salio mal
Vamos a solucionarlo. Intenta mas 
[Link Error](https://drive.google.com/open?id=10bpPH3CI-Ay90brgQV3nBroujsQYAig4)

private static final int REQUEST_CODE = 1
new MercadoPagoCheckout.Builder(PUBLIC_KEY_SANDBOX,
                "565939008-fcef652f-81f2-475b-8638-44b4da4f4f4e")  <-- PreferencedID valida
                .setAdvancedConfiguration(advancedConfiguration)
                .build()
                .startPayment(this, REQUEST_CODE);
Anexo foto
[Link ID](https://drive.google.com/open?id=1BsDTxZtWupRgzRF7zPIgLZqKCBsulGfN)

Lo estoy generando desde una actividad principal
al momento de generar el error, obtengo el data siempre null

if (requestCode == REQUEST_CODE) {
            if (resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE) {
                final Payment payment = (Payment) data.getSerializableExtra(MercadoPagoCheckout.EXTRA_PAYMENT_RESULT);
                mp_results.setText("Resultado del pago: " + payment.getPaymentStatus());
            } else if (resultCode == RESULT_CANCELED) {
                if (data != null && data.getExtras() != null
                        && data.getExtras().containsKey(MercadoPagoCheckout.EXTRA_ERROR)) {
                    final MercadoPagoError mercadoPagoError =
                            (MercadoPagoError) data.getSerializableExtra(MercadoPagoCheckout.EXTRA_ERROR);
                    mp_results.setText("Error: " +  mercadoPagoError.getMessage());
                    mp_results.setVisibility(View.VISIBLE);
                    //Resolve error in checkout
                } else {
                    //Resolve canceled checkout
                }
            }
        }

Alguien podria ayudarme

**Comment by MrBrightzide** [comment]
Tengo este mismo error, alguien pudiera asesorarme por favor?

**Comment by yonemec** [comment]
> Hola Uso la libreria 'com.mercadopago.android.px:checkout:4.44.0' cuando inicio el .startPayment sale la pantalla ALgo Salio mal Vamos a solucionarlo. Intenta mas [Link Error](https://drive.google.com/open?id=10bpPH3CI-Ay90brgQV3nBroujsQYAig4)
> 
> private static final int REQUEST_CODE = 1 new MercadoPagoCheckout.Builder(PUBLIC_KEY_SANDBOX, "565939008-fcef652f-81f2-475b-8638-44b4da4f4f4e") <-- PreferencedID valida .setAdvancedConfiguration(advancedConfiguration) .build() .startPayment(this, REQUEST_CODE); Anexo foto [Link ID](https://drive.google.com/open?id=1BsDTxZtWupRgzRF7zPIgLZqKCBsulGfN)
> 
> Lo estoy generando desde una actividad principal al momento de generar el error, obtengo el data siempre null
> 
> if (requestCode == REQUEST_CODE) { if (resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE) { final Payment payment = (Payment) data.getSerializableExtra(MercadoPagoCheckout.EXTRA_PAYMENT_RESULT); mp_results.setText("Resultado del pago: " + payment.getPaymentStatus()); } else if (resultCode == RESULT_CANCELED) { if (data != null && data.getExtras() != null && data.getExtras().containsKey(MercadoPagoCheckout.EXTRA_ERROR)) { final MercadoPagoError mercadoPagoError = (MercadoPagoError) data.getSerializableExtra(MercadoPagoCheckout.EXTRA_ERROR); mp_results.setText("Error: " + mercadoPagoError.getMessage()); mp_results.setVisibility(View.VISIBLE); //Resolve error in checkout } else { //Resolve canceled checkout } } }
> 
> Alguien podria ayudarme

Hola.
pudiste resolver el problema? Si tienes algo de info, te agredeceria! Gracias!

**Comment by antonioreyna** [comment]
resolvieron el problema?

**Comment by yonemec** [comment]
Si, muchas  gracias
