### ISSUE TITLE
Can i charge with savd card?

### ISSUE THREAD

**Issue by tes1oner** [mercadopago/px-android#196]
Using px-android method can i charge with saved cards as the sdk-android in this tutorial https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/one-click-charges/android/ ?? 
Sorry for ask here, mercadopago have not suport or actives comunities -.-

**Comment by matiasromar** [comment]
Hi @tes1oner ! 
Saved cards will be available soon on next release for our standard checkout. Actually, this feature is developed so you can try it and see how is the flow but you will not can to create a payment. 
For this, you have to start our Checkout with this code:

`
private void startMercadoPagoCheckout() {
   
        new MercadoPago.StartActivityBuilder()
                .setActivity(this)
                .setPublicKey(mPublicKey)
                .setCheckoutPreferenceId(mCheckoutPreference.getId())
                .setMerchantBaseUrl("https://www.mercadopago.com") //Optional
                .setMerchantGetCustomerUri("/checkout/examples/getCustomer") //Optional
                .setMerchantAccessToken("mlv-cards-data") //Optional
                .startCheckoutActivity();
    }
`

**Comment by tes1oner** [comment]
Thanks  @matiasromar i will try.!
