### ISSUE TITLE
The lib is overriding the FAB color and icon position

### ISSUE THREAD

**Issue by newcaiosantos** [mercadopago/px-android#1983]
When I am editing my layout, the FAB appears correctly, however when I compile for the simulator, the FAB turns blue. I did the test and simply removing the lib (implementation 'com.mercadopago.android.px: checkout: 4. +') all back to normal. I also customized the color (<color name = "ui_components_android_color_primary">) and nothing is reflected. The problem is not only with the color, but with the icon position too. I want it to stay in the center, but it stays  in the lower right corner.

**Comment by guchito9** [comment]
What style are you using in your Activity?

**Comment by gsanguinetti** [comment]
Same thing here. The sdk is currently broken the native fab.

**Comment by dslpos** [comment]
Same thing here. Anyone was able to fix this?

**Comment by fivunlm** [comment]
Same here. Anyone was able to fix this?

**Comment by guchito9** [comment]
Hi, the icon position seems to be a bug with support library 28.x:
https://stackoverflow.com/questions/52635233/floating-action-button-icon-not-centered-inside/52967921

And for the color, it seems to be replaced in style by some dependency of ours.

You can solve both problems using this:
`app:backgroundTint="@android:color/holo_green_dark"
app:maxImageSize ="56dp"`

**Comment by gsanguinetti** [comment]
> Hi, the icon position seems to be a bug with support library 28.x:
> https://stackoverflow.com/questions/52635233/floating-action-button-icon-not-centered-inside/52967921
> 
> And for the color, it seems to be replaced in style by some dependency of ours.
> 
> You can solve both problems using this:
> `app:backgroundTint="@android:color/holo_green_dark"`
> `app:maxImageSize="56dp"`

NO, I'd written this question in StackOverflow when I detected it a couple years ago. All that answers are wrong. This bug is is fully fully related with this MercadoPago library and isn't a Support Library bug.

**Comment by guchito9** [comment]
Well, I tried the fix right there in my comment and works just fine, have you tried it?

**Comment by guchito9** [comment]
![Screenshot_1594919190](https://user-images.githubusercontent.com/44264058/87700987-9d248380-c76d-11ea-80d9-eb7e09c28278.png)

Here is with support 27.1.1, working just fine

**Comment by gsanguinetti** [comment]
> Well, I tried the fix right there in my comment and works just fine, have you tried it?

I'm not currently using this library no more. But, as far I can see, your answer is actually  proposing a workaround but not a valid fix for this bug. You are reapplying a style to the FAB that overrides the default value, which is previously overriden by the MercadoPago library for some reason broking the FAB layout. 
In my opinion, this issue should be closed when somebody who imports this MercadoPago library doesn't need to include those attributes to the FAB in order to get it working as expected.

**Comment by guchito9** [comment]
I said that the color thing is a problem with a dependency or ours and proposed a workaround, yes.

But the position problem is not from our library, and you very firmly said it is with no proof at all. Even saying all the people that answered you on StackOverflow are wrong.

**Comment by gsanguinetti** [comment]
> I said that the color thing is a problem with a dependency or ours and proposed a workaround, yes.
> 
> But the position problem is not from our library, and you very firmly said it is with no proof at all. Even saying all the people that answered you on StackOverflow are wrong.

Yes, I've tested every workaround when I asked this question a couple of years and concluded this is happening when I imported the MP library, regardless of the Support library version. As I said, the fix should leverage devs from re applying this attributes on the FAB when importing the MP library

**Comment by gsanguinetti** [comment]
+@cazador4
