### ISSUE TITLE
Qué pasa si mi API no tiene https?

### ISSUE THREAD

**Issue by tes1oner** [mercadopago/px-android#203]
Necesito setear la url de notificación para poder agregar el pago en mi BD(PHP), pero cuando intento agregar la url en: https://www.mercadopago.com.ve/ipn-notifications/save
me responde La URL ingresada no responde un HTTP status correcto. Debe responder 200 o 201.
Obviamente la api sí responde con ese código, pero leyendo lo siguiente: [https://wordpress.org/support/topic/la-url-ingresada-no-responde-un-http-status-correcto-debe-responder-200-o-201/](https://wordpress.org/support/topic/la-url-ingresada-no-responde-un-http-status-correcto-debe-responder-200-o-201/) dice que:
SSL is a need if you are using custom checkout or tickets, because it is your server that processes the payment with sensitive data. So, it became a security standard.

Es realmente necesario tener el certificado ssl ? 
Dice que si estoy usando un checkout básico no lo necesito, realmente no sé si este método es considerado el checkout básico, estoy usando px-android y el sdk-php

**Comment by mreverter** [comment]
Te dejo un contacto de integraciones: 
micaela.greisoris@mercadopago.com

Saludos, 
Mauro.

**Comment by joelibaceta** [comment]
@tes1oner , respondo brevemente a tus interrogantes : 

- Efectivamente, si vas a realizar procesamiento de informacion de pagos desde tu servidor (sdk php) es necesario e importante que cuentes con un certificado SSL por seguridad (https://www.mercadopago.com.ar/developers/en/api-docs/basic-checkout/ipn/).
- Si usas un checkout basico no es necesario, esto debido a que el procesamiento del pago se lleva a cabo dentro de una interfaz controlada por MercadoPago en una ventana externa o embebida (iframe).
- La diferencia entre checkout basico y personalizado, es : 
  - **Checkout Basico** : Nuestra sugerencia de mejor experiencia y formulario de pagos pre construido con la UI de MercadoPago, para realizar un pago con esta opcion debes crear una preferencia y redirigir al usuario al formulario de pagos.
  - **Checkout Personalizado** : Usas las sdks o realizas una integracion via API para tener un formulario de pagos totalmente personalizado.

**Comment by tes1oner** [comment]
@joelibaceta Gracias por responder. Tengan en cuenta que el foro está abandonado. Por acá por github es la única forma que me respondan.
