### ISSUE TITLE
MercadoPagoCheckout.startPayment(...) always ends in a Something went wrong screen

### ISSUE THREAD

**Issue by Gazer** [mercadopago/px-android#2123]
I'm using an application created with my account. Get the public key and access token. With the token, I've created a preference with PHP and get the ID.

```php
  MercadoPago\SDK::setAccessToken("A_TOKEN");

  $preference = new MercadoPago\Preference();

  $item = new MercadoPago\Item();
  $item->title = "Rustic Bronze Watch";
  $item->quantity = 2;
  $item->currency_id = "ARS";
  $item->unit_price = 13.33;

  $payer = new MercadoPago\Payer();
  $payer->email = "test_user_19653727@testuser.com";

  $preference->items = array($item);
  $preference->payer = $payer;
  $preference->save();

  echo $preference->id . "\n";
```
Then on my android test android app I call:
```kotlin
MercadoPagoCheckout.Builder(publicKey, preferenceId).build().startPayment(this, CODE)
```
The payment flow stars, I can select credit card and add the data, or bank account or pay at the kiosk, etc. Also, I can see the item price, total quantity, etc. So the SDK is reading the preference from the server.

In the final screen, I get all the data to review and press pay, no matter what, I get this screen:

<img width="468" alt="Screen Shot 2020-04-23 at 15 50 02" src="https://user-images.githubusercontent.com/4705/80146023-8663fb80-8587-11ea-8cf5-c20dd336fab8.png">

No logs or errors in the device Logcat. I'm using the latest version (4+) but also tried some older versions.

I've tested the project with and without AndroidX and with different versions of the support library.

Additionally, I've added to the build.gradle: 

```gradle
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
```

Right now I'm not sure if the problem is in the SDK or my setup because I've followed all the steps in the documentation.

**Comment by Gazer** [comment]
The problem seems to be the email address used to create the preferenceId, if I change ` $payer->email = "test_user_19653727@testuser.com";` in the PHP code and re-test the app works as expected.

Any idea why an email makes the checkout fail?

**Comment by cgaggino** [comment]
Hey @Gazer, how are you?

A common problem with the email is that the email should not be equal to the user's email of public key. It is intended to be the email of user buying and a user cant sell and buy to himself

I'm looking forward to know if it was the case

**Comment by Gazer** [comment]
No, the email does not match in this case, the value used to create the preference was "test_user_19653727@testuser.com" that is in the SDK documentation.

**Comment by cgaggino** [comment]
Then it may be outdated, can you refer me to which documentation are you viewing?

**Comment by Gazer** [comment]
> Then it may be outdated, can you refer me to which documentation are you viewing?

The email that fails was copied from https://www.mercadopago.com.ar/developers/es/guides/payments/mobile-checkout/receive-payments/. I'll close the issues. Thanks

**Comment by MartinRValdez** [comment]
Estoy teniendo el mismo problema, se encontró solucion?
