### ISSUE TITLE
Agregar salto de línea antes del monto en título de pantallas de resultado.

### ISSUE THREAD

**Issue by mreverter** [mercadopago/px-android#215]
Para evitar que se vea cortado el monto.

**Comment by matiasromar** [comment]
![screen shot 2016-11-29 at 1 30 57 pm](https://cloud.githubusercontent.com/assets/4195740/20718729/7486c518-b638-11e6-8610-724e69619bbb.png)
![screen shot 2016-11-29 at 1 27 13 pm](https://cloud.githubusercontent.com/assets/4195740/20718731/7487fcb2-b638-11e6-81f0-6392c2ad6574.png)
![screen shot 2016-11-29 at 1 24 15 pm](https://cloud.githubusercontent.com/assets/4195740/20718730/74877616-b638-11e6-8b54-f9f01f739739.png)
