### ISSUE TITLE
NullPointerException desde 4.45.1

### ISSUE THREAD

**Issue by marianoarga** [mercadopago/px-android#2175]
Hola, desde la version 4.45.1 en adelante que recibo
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mercadopago.android.px.model.PaymentMethod.getPaymentTypeId()' on a null object reference`
al finalizar la carga de la tarjeta e iniciar MercadoPagoCheckout.Builder

UPDATE: No esta pasando en el tag 4.45.3 que subieron hace unos minutos.

**Comment by guchito9** [comment]
Hola Mariano, lo acabamos de fixear como viste, mil disculpas!

**Comment by marianoarga** [comment]
@guchito9 gracias.
Consulta, que diferencia al 4.45 del 4.46, que veo que van generando en paralelo?

**Comment by guchito9** [comment]
Deberías usar la 4.46.x
Le seguimos dando soporte a la 4.45 porque todavía está prendida en producción en la app de Mercado Pago.
