### ISSUE TITLE
Pagos pendientes, posteriormente rechazados (cc_rejected_high_risk)

### ISSUE THREAD

**Issue by marianoarga** [mercadopago/px-android#2180]
Todas las transacciones donde el metodo de pago no sea Visa Debito estan respondiendo como pendientes para posteriormente (ya lo vengo testeando hace dias y dias) terminar en rechazado y la razon **cc_rejected_high_risk**
Multiples tickets en https://www.mercadopago.com.ar/ayuda no logran ayudarme a descifrar el porque y por esta razon me dirigo a lo tecnico. Podrian indicarme si hay algun paso que estoy omitiendo, algun parametro fuera de lugar?, **porque ciertos pagos (Visa Debito) pasan como si nada y el 99% restante de otros pagos no pasan**?
Adjunto imagen, los dias anteriores son una lista larga de rechazados, se puede ver el comienzo ahi debajo.
![image](https://user-images.githubusercontent.com/1138627/83781939-93373d00-a665-11ea-85e9-95d13e2f563e.png)

Probe utilizando el mismo preference/payer, probe variandolo, el resultado es el mismo.

Preference que se crea, (reemplazo datos sensibles por {{DATO}}):
```
{
   "items":[
      {
         "title":"COEGV",
         "quantity":1,
         "currency_id":"ARS",
         "unit_price":2910.79
      }
   ],
   "payer":{
      "name":"Alejandro Daniel",
      "surname":"GIL",
      "email":"{{DATO}}",
      "phone":{
         "area_code":,
         "number":"{{DATO}}"
      },
      "identification":{
         "type":"DNI",
         "number":"{{DATO}}"
      }
   },
   "payment_methods":{
      "excluded_payment_types":[
         {
            "id":"ticket"
         },
         {
            "id":"atm"
         }
      ]
   },
   "additional_info":"Alejandro Daniel GIL",
   "external_reference":1010_1224_08-0413093
}
```

email es un email valido como "alguien@server.com"
phone.number es un dato como "2345678902"
identification.number es un dato como "22.158.125"

Muchas gracias.

**Comment by Russi96** [comment]
Tengo el mismo problema que se puede hacer

**Comment by vitito93** [comment]
@marianoarga lograste solucionarlo? Tengo entendido que ese cc_rejected_high_risk es para prevención de fraude y 'en teoría' se soluciona enviando mas información, como datos del payer, items, etc.
Llegué acá porque estoy con el mismo problema, en la semana voy a probar añadiendo esta data a ver si logramos mejorar el % de aprobados, acá mas data: 
[](https://www.mercadopago.com.ar/developers/es/guides/manage-account/account/payment-rejections)

**Comment by catrielmercurio** [comment]
Amigos, pudieron solucionar esto? Me esta volviendo loco...

**Comment by cgaggino** [comment]
Hola chicos como andan? tendrán para pasarnos algunos payment ids rechazados para que se los pasemos al equipo de fraude y ver como podemos ayudarlos?

Saludos!

**Comment by catrielmercurio** [comment]
@cgaggino Si claro 13414078253 o 13405653288

**Comment by jcarizza42** [comment]
Hiice 4 pagos con la tarjeta exitosos, pero cuanto quiero hacer el pago recurrente no funciona.. me devuelve el error cc_rejected_high_risk

**Comment by marianoarga** [comment]
@everyone la unica manera que tuvo el cliente de reparar tantos rechazados fue aumentar el plazo para cobrar, ej. si tenia configurado para cobrar en 1 semana, lo paso a 1 mes y santo remedio, nunca nadie de MP nos supo decir el porque ni los dio la solucion, fue pura suerte de cambiar eso en nuestro caso.

Saludos.

**Comment by josecarvajal8** [comment]
Hola, estoy teniendo el mismo problema, a pesar de tener los plazos en lo máximo (30 días) sigo teniendo el mismo error `cc_rejected_high_risk`, alguno ha tenido algun tipo de avance con este tema? Segun vi en un foro de google una persona recomienda crear una nueva application.  https://groups.google.com/g/mercadopago-developers/c/CY4VAhekK8c/m/MV0p3pFWCgAJ
