### ISSUE TITLE
marketplace_fee en Android

### ISSUE THREAD

**Issue by josequintana94** [mercadopago/px-android#2194]
Buenas noches, con mi equipo estamos usando marketplace para que los usuarios reciban los pagos en sus cuentas, y funciona perfecto en web.

En Android, los pagos llegan perfecto a cada uno de los usuarios, lo que no funciona es el **marketplace_fee**. No se esta aplicando el fee cuando realizo el pago desde Android, solo aplica el fee de MercadoPago.

Hay alguna forma de que se active el marketplace_fee tambien cuando hago el checkout en Android? Saludos

**Comment by ibanezjp** [comment]
+1

**Comment by cgaggino** [comment]
@josequintana94 @ibanezjp como andan? lamentablemente no está implementado este feature y no vamos a estar dando soporte a features nuevos probablemente hasta el proximo major de la SDK pero es algo que no va a suceder a corto plazo.

Cierro el ticket pero no duden en abrir otro si tienen mas consultas.

Saludos!
