### ISSUE TITLE
[Consulta] - Guardar y Recuperar Tarjetas cargadas

### ISSUE THREAD

**Issue by JonatanSalas** [mercadopago/px-android#2195]
**¿Es posible guardar y recuperar tarjetas por medio de este SDK?**

Entiendo que para web existe ya soporte de esto mediante el [Web Tokenize Checkout](https://www.mercadopago.com.ar/developers/es/guides/payments/web-tokenize-checkout/introduction/).

En caso de que se pueda, **¿Existe alguna documentación o guideline sobre cómo implementarlo?**

Nos gustaría poder usar el SDK nativo de Android, pero, si esto no se puede realizar, deberíamos migrar a implementar una **WebView** con **Web Tokenize Checkout**.

Desde ya muchas gracias.

**Comment by guchito9** [comment]
Buenas, por ahora no tenemos en el scope soportar algo así en este sdk :(

**Comment by OCTVRM** [comment]
Existe la forma de usar de manera de prueba, sin necesidad que solicite una BD firebase pagada?

**Comment by JonatanSalas** [comment]
@guchito9 tienen pensado soportarlo en alguna iteración de la v4, o está muy muy lejos de verse implementado esto?

**Comment by cgaggino** [comment]
Hola @JonatanSalas, tenemos pensado implementar una integración donde el usuario pueda pagar con las tarjetas de su wallet si es que tiene user pero mas a largo plazo, probablemente en un v5. Como ya comentó @guchito9 con la versión actual no es posible.

Cierro el ticket pero no dudes en abrir otro si tenes alguna otra consulta

Saludos!

**Comment by MuriloPetruci** [comment]
Hi friends.  @JonatanSalas you were able to generate the card hash using WebView and Web Tokenize Checkout ?

**Comment by JonatanSalas** [comment]
@MuriloPetruci I'm working on a library for react-native that uses Web Tokenize Checkout + WebView, that I'm going to free up in almost 2 weeks.

**Comment by MuriloPetruci** [comment]
you want help ?

**Comment by MuriloPetruci** [comment]
I'm almost done with an integration. if you take a look at the code it might help you with something

**Comment by JonatanSalas** [comment]
@MuriloPetruci I want some help! Would be glad to see how you managed to integrate it!

**Comment by antonioreyna** [comment]
entonces cual sería el flujo correcto a implementar para poder tener la experiencia completa de pago con mercadopago? webview y llamar la url de init_point?
