### ISSUE TITLE
Únicos medios disponibles - Pagos con tarjeta, 

### ISSUE THREAD

**Issue by Jcmouy** [mercadopago/px-android#2210]
Hola, en primer lugar disculpen las molestias, estoy comenzando a integrar el checkout en mi app, y me encuentro que el usuario vendedor que poseó, los unicos medio disponibles que tiene son pagos por medio de tarjetas de credito. Adjunto imagen de esto.

![2020-06-28 11_56_22-Window](https://user-images.githubusercontent.com/10815551/85951071-2c8d0280-b937-11ea-8f16-82fbc500fc62.png)

Quería saber como hago para habilitar otros? Aprovecho para consultarlos tambien como hago para cambiar el idioma, ya que por defecto toma el ingles.

Desde ya muchas gracias.

**Comment by cgaggino** [comment]
Hola @Jcmouy todo bien? No es ninguna molestia.

Los medios disponibles para pagos de usuarios guest son tarjetas de crédito, débito y medios off (rapipago, pagofacil si es una preferencia de argentina o boleto, pec si es preferencia de brasil, por ejemplo) Entiendo por el screen que pasaste que esos tampoco te aparecen? podras pasarnos los datos del vendedor como el mail y la preferencia de pago que usaste?

En cuanto al idioma, toma por defecto el que está configurado en el celular, es lo más recomendado en Android. Podrias intentar pisar el locale en tu aplicación para que la lib tome otro

**Comment by Jcmouy** [comment]
Hola @cgaggino , lo más bien y tu? En primer lugar muchas gracias por responder. Siguiendo tus indicaciones logre resolver el problema del idioma. 

Si, sinceramente me llama la atención que no me aparezcan los otros medios de pago disponible. Para el caso de transferencia bancaria ya tendria que estar en producción no? Te paso los datos del vendedor como me pediste:

Email: "jcm@gmail.com"
PreferenceId: 61081159-ff2ae334-2a4f-4260-a02c-9d0c563b02d1

Por si te resulta de utilidad te paso tambien la public key:

Public Key: TEST-241acaec-4118-477f-83eb-f66837e68fed

Desde ya muchas gracias!

**Comment by Jcmouy** [comment]
Hola @cgaggino , con fines de prueba me cree otro preference id, pero el resultado fue el mismo.

PreferenceId: 61081159-99b3dce1-1d65-4299-b30f-d6cde84f1b6a
PayerEmail: compra@gmail.com

El public key es el mismo del mensaje anterior, y el vededor es mi usuario de mercadopago, email: jcmouy@gmail.com

**Comment by cgaggino** [comment]
Hola @Jcmouy, estuve analizando tu caso, y entendi que el site del collector es Uruguay, lamentablemente en Uruguay no soportamos medios off en la sdk nativa, por el momento solo vas a poder integrar para pagos con tarjetas.

Lamento los inconvenientes que esto te pueda ocacionar.

**Comment by Jcmouy** [comment]
Por favor, no pasa nada, te agradezco igualmente por las molestias! Trabajaremos de esa manera por ahora entonces. Muchas gracias!
