### ISSUE TITLE
Enlazar un cliente con una tarjeta o varias desde el sdk Android 

### ISSUE THREAD

**Issue by cesarwillymc** [mercadopago/px-android#2226]
Por el momento vi que es necesario desde el sdk pasar el preferenceId  creada, pero quisiera saber si hay una forma de seguir estos pasos en android:
1:  Crear Datos de Usuario (Payer)
2:  Que de esos datos te salgan el sdk de mercado de pago o una interfaz creada con un token para introducir tarjeta.
3: Que se guarde la tarjeta mediante el id y el cliente
4: Seleccionar una tarjeta creada con un usuario y realizar el pago mediante el sdk.

Estoy usando Android nativo. 
Hay una forma o es necesario que se haga en una web esos pasos, para realizarlo con un webView desde android esa parte.
Gracias de antemano

**Comment by cgaggino** [comment]
Buenas @cesarwillymc lamento decirte que el SDK esta preparado para pagos guest, es decir que no obtiene ni mantiene información de un payer particular, tenemos en mente incluir una integración para que el usuario pueda loguearse con sus credenciales y usar sus medios pero no lo tenemos en roadmap a corto plazo

Saludos!

**Comment by cgaggino** [comment]
Procedo a cerrar el ticket, no dudes en abrir otro si tenes otra consulta!

Saludos!
