### ISSUE TITLE
Incompatible con CameraView

### ISSUE THREAD

**Issue by K-ballo** [mercadopago/px-android#2229]
No es posible utilizar esta libreria en conjunto con `androidx.camera.view.CameraView`, dado que ambas librerias definen un atributo `scaleType`.

Para reproducir, agregar las siguientes dependencias a un mismo proyecto:

```
implementation 'com.mercadopago.android.px:checkout:4.51.0'
implementation 'androidx.camera:camera-view:1.0.0-alpha13'
```

**Comment by guchito9** [comment]
Buenas, nosotros directamente no definimos ningún atributo `scaleType`, debe ser alguna dependencia que tengamos.

Fijate acá como podés hacer para que convivan las dos:
https://developer.android.com/studio/write/add-resources.html#resource_merging

**Comment by K-ballo** [comment]
> Buenas, nosotros directamente no definimos ningún atributo `scaleType`, debe ser alguna dependencia que tengamos.

En efecto, el atributo está definido dentro del styleable `MLImage` (`ML` = Mercado Libre?).

> Fijate acá como podés hacer para que convivan las dos:
> https://developer.android.com/studio/write/add-resources.html#resource_merging

No encuentro como hacer que convivan las dos. Tampoco me imagino como sería posible que convivan, siendo que ambas librerias exportan el attributo `app:scaleType` con valores incompatibles. Cómo se supone que mi aplicación utilizaría tanto `app:scaleType` de `CameraView` como `app:scaleType` de `MLImage` al mismo tiempo?

**Comment by guchito9** [comment]
Mirá, lo único que se me ocurre que podrías hacer, es cambiar el nombre del atributo en la lib que tenemos como dependencia con el problema:
https://github.com/mercadolibre/fury_mobile-android-ui

Y generarte una versión con el nombre cambiado
