### ISSUE TITLE
Checkout mobile Android

### ISSUE THREAD

**Issue by hninor** [mercadopago/px-android#2236]
Buenas tardes,

Me sale un mensaje de Algo salió mal, vamos a solucionarlo. Intenta más tarde
![Screenshot_2020-07-20-12-40-30-421_com hninor barberiaapp](https://user-images.githubusercontent.com/21149918/87969087-18947680-ca87-11ea-9fe1-099d3d5359ca.jpg)

**Comment by hninor** [comment]
Esta es mi  PUBLIC_KEY TEST-29a540d8-4d4f-44ab-9495-be4a51eb132c

**Comment by cgaggino** [comment]
Hola @hninor, podras pasarme tambien el pref id que creaste?

**Comment by hninor** [comment]
PREF_ID 139895537-525429a4-9da6-4fa8-836c-b54dd176bd87

**Comment by hninor** [comment]
Gracias por la respuesta, es decir, yo no puedo dejar un pago abierto para cualquier comprador

**Comment by cgaggino** [comment]
Deberias crear una preferencia para cada pago, pero podes si la dejas asociada a un mail que no exista

**Comment by hninor** [comment]
Buenas tardes

{
    "items": [
        {
            "id": "item-ID-1234",
            "title": "Title of what you are paying for. It will be displayed in the payment process.",
            "currency_id": "COP",
            "description": "Item description",
            "category_id": "art", // Available categories at https://api.mercadopago.com/item_categories
            "quantity": 1,
            "unit_price": 1000
        }
    ],
    "payer": {
        "email": "test_user_11925572@testuser.com"
    },
    "payment_methods": {
        "excluded_payment_methods": [
            {
                "id": ""
            }
        ],
        "default_installments": null,
        "default_payment_method_id": null,
        "excluded_payment_types": [
            {
                "id": ""
            }
        ],
        "installments": null
    }
}

Estoy usando está configuración y en los medios de pago no me aparece PSE, Mercado pago, estoy en Colombia

**Comment by hninor** [comment]
Por favor su colaboración

**Comment by cgaggino** [comment]
Hola @hninor, lamentablemente no soportamos este medio en las sdks nativas

**Comment by cgaggino** [comment]
@hninor procedo a cerrar el ticket, cualquier otra pregunta no dudes en abrir otro ticket

Saludos!
