### ISSUE TITLE
Como genero el Token desde la aplicación

### ISSUE THREAD

**Issue by Russi96** [mercadopago/px-android#2249]
Buenas tardes 

Quisiera saber de que forma puedo generar el token desde la aplicacion movil

**Comment by xavieralex82** [comment]
Hola Russi96: Lo ideal es que lo hagas en tu servidor
Te paso los método POST de llamada

curl -X POST \
     'https://api.mercadopago.com/checkout/preferences?access_token=ACCESS_TOKEN' \
     -H 'Content-Type: application/json' \
     -d '{
           "items": [
               {
               "title": "Dummy Item",
               "description": "Multicolor Item",
               "quantity": 1,
               "currency_id": "ARS",
               "unit_price": 10.0
               }
           ],
           "payer": {
               "email": "payer@email.com"
           }
     }'

**Comment by cgaggino** [comment]
Hola @Russi96 y @xavieralex82, gracias por responder, entiendo que lo que quiere Russie es obtener el token del payer, y lo que vos le pasaste es armar la preferencia

@Russi96 si entendí bien, lo que querés hacer no es posible, la firma que recibe un access token es de uso interno solamente.

Cierro el ticket pero no dudes en abrir otro si te quedan mas dudas!

Saludos!
