### ISSUE TITLE
Minimum Android SDK version

### ISSUE THREAD

**Issue by dantti** [mercadopago/px-android#2253]
What the current minimum SDK version.
I've been trying to include the project it complained that API 19 was required, then showed some errors about usage of API 24 and 26, and even raising to 26 (which is a no go for me as the market share of lower versions is still very high) it didn't work.

**Comment by xavieralex82** [comment]
Hola dantti, me paso lo mismo hasta la API 19 pero luego se quejo. Tiene que ver cuando tu app y las bibliotecas a las que hace referencia superan los 65,536 métodos, se produce un error de compilación que indica que la app alcanzó el límite de la arquitectura de compilación de Androdi entonces deberías agregar  multiDexEnabled  en "true" en tu build.gradle (modulo app)
referencia de problema: https://developer.android.com/studio/build/multidex      

//agregar esto en defaultConfig de tu  build.gradle (modulo app)
  defaultConfig {

        multiDexEnabled true
  
    }

**Comment by cgaggino** [comment]
Hola @dantti y @xavieralex82, gracias por responder, si nos pasó el ticket

Te dejo otra sugenrencia a la que puse xavier para que tengas en cuenta. puede ser que haga falta configurar el proyecto para java 1.8, por ejemplo: 

`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`

`kotlinOptions {
        jvmTarget = "1.8"
    }`

**Comment by cgaggino** [comment]
Cierro el ticket si necesitas mas ayuda no dudes en abrir otro! saludos

**Comment by dantti** [comment]
You still don't answer the main question, what's the minimum Android API target? Is it 19?

And yes, I have set Java 1.8 but still it don't compile, mutidex is a bad solution as it increases APK size and is only needed if you don't set the same jvm target.

**Comment by cgaggino** [comment]
Hi @dantti, the minimum API level is 19, you can check it out how it is working in our example app
