### ISSUE TITLE
Error al realizar el pago en la aplicación

### ISSUE THREAD

**Issue by johandavidcm** [mercadopago/px-android#2472]
Versión Android: 10

Buenas tardes, tengo el siguiente inconveniente, estoy intentando realizar el pago en mi aplicación pero no funciona, estoy utilizando las credenciales de prueba. y me arroja la siguiente pantalla a la hora de pagar.

![error](https://user-images.githubusercontent.com/62624815/114438058-e08d1080-9b8c-11eb-9b77-70125a7b8bc4.jpg)

No obtengo ninguna retroalimentación del error para saber que estoy haciendo mal. lo único que obtengo de la consola es lo siguiente.

`com.mercadopago.android.px.internal.features.review_and_confirm.ReviewAndConfirmActivity@bdb685d`

Cabe resaltar que estoy utilizando el SDK de flutter para realizar mi aplicación pero estoy implementando nativamente el px-android, en mi `build.gradle` tengo la siguiente versión ` implementation 'com.mercadopago.android.px:checkout:4.+'`

Y también cabe resaltar que hace una semana aproximadamente si me estaba funcionando correctamente la implementación que tenía.

Agradecería mucho la ayuda para solucionar este inconveniente.

**Comment by LeoCBS** [comment]
I am with same error here.. console don't show any error message... just one red pop up on application.. do you found the solution? @johandavidcm

**Comment by johandavidcm** [comment]
@LeoCBS Yes, the problem was that when creating the Preference ID, in the "payer" field, I was putting in the email an email that belongs to a Mercadopago account. In the test mode it is not allowed for some reason that I disagree. But when it goes into production it works perfectly. That is, the payer object should look like this:

Development:

```
payer = {
    email: 'test@test.com',
    name: 'Nombre usuario'
}
```

Production:

```
payer = {
    email: 'productionemail@production.com',
    name: 'Nombre usuario'
}
```
In the second you must put the client's email and in the first one some invented email.

**Comment by LeoCBS** [comment]
thanks for your reply @johandavidcm.  I created two test users using this "https://api.mercadopago.com/users/test_user" and worked fine here too... but all errors on the checkout process will show just one red popup without information? how did you discover that the error was payer e-mail? how will the final user's discovery checkout errors if mercadopago don't show any error?

**Comment by johandavidcm** [comment]
No the only problem that i found without information was these one. 
And i figure out searching a lot, I don't remember in what pages I found the solution
And MercadoPago shows all the errors. I only had problems with this one.
