### ISSUE TITLE
Se pinta el borde de la tarjeta de otro color

### ISSUE THREAD

**Issue by edentorres** [mercadopago/px-android#260]
En el formulario de tarjeta, cuando lo abris con un color y despues lo volves a abrir sin color pasa esto:

![screenshot_1481745828](https://cloud.githubusercontent.com/assets/9399970/21198767/5b7353a0-c21f-11e6-953f-badfe84a01e2.png)

**Comment by mreverter** [comment]
Agregado al tablero! Queda como low priority porque es un caso muy excepcional que seteen un color y después no lo hagan ante otro inicio.
