### ISSUE TITLE
Need to migrate from Jcenter

### ISSUE THREAD

**Issue by danielechizen** [mercadopago/px-android#2648]
The px-android and dependencies need to be migrated from jcenter. We can't use sdk anymore cause is impossible to fetch the package and dependencies from mercadopago and mercadolibre group on gradle.
There is some scheduling, since jcenter was completely deactivated on February 1st.

**Comment by vilmarbfilho** [comment]
Same here. I work in a project that use `px-services`. 
Here we go to clone this repo and create a side lib.
I would also like to know when they intend to migrate.

**Comment by prodriguez96** [comment]
Hello, I have the same problem, do you have any solution for this?

**Comment by vilmarbfilho** [comment]
Hi @prodriguez96!
Here I created a new module just for Mercado Pago requests. Extract the code that is used in the project, in some cases I had to rewrite the code because the class in `px-services` was java code.

It is very sad that no one from Mercado Pago responds to this thread.

**Comment by prodriguez96** [comment]
Thanks a lot! Now I try your suggestion, I hope it works

**Comment by guchito9** [comment]
Hi, Jcenter will continue to work as a read-only repository indefinitely, so we would need to migrate from that in case of releasing new public versions only.
