### ISSUE TITLE
MERCADOPAGO -ANDROID 12

### ISSUE THREAD

**Issue by shagiGTT** [mercadopago/px-android#2663]
Hello, I have mercadopago integrated into my app, however when uploading it to google play it gives me an error, since in the activity CheckoutActivity I cannot add the line android:exported that forces you to have ANDROID 12, do you know of any solution?

**Comment by guchito9** [comment]
Hi Shagi, you should target api 30 to use this sdk, at least until we make the changes to add those fields to our activities.
