### ISSUE TITLE
Could not resolve com.mercadopago.android.px:checkout:4.+

### ISSUE THREAD

**Issue by NWare00** [mercadopago/px-android#2665]
Hola! estoy tratando de integrar el checkout pero obtengo un error al tratar de importar la dependencia.

`Could not resolve com.mercadopago.android.px:checkout:4.+.
     Required by:
         project :app
      > Failed to list versions for com.mercadopago.android.px:checkout.
         > Unable to load Maven meta-data from [https://google.bintray.com/exoplayer/com/mercadopago/android/px/checkout/maven-metadata.xml]().
            > Could not get resource '[https://google.bintray.com/exoplayer/com/mercadopago/android/px/checkout/maven-metadata.xml]()'.
               > Could not GET '[https://google.bintray.com/exoplayer/com/mercadopago/android/px/checkout/maven-metadata.xml]()'. Received status code 502 from server: Bad Gateway`

tienen pensado migrar de jcenter y usar otro repositorio? está causando muchos problemas esto

**Comment by guchito9** [comment]
Hola, por lo menos hasta que volvamos a sacar versiones públicas no está en los planes. Por favor fijate de tener bien configurado los repositorios y no deberías tener problemas.

**Comment by guchito9** [comment]
Si es un proyecto con una versión de Gradle mayor a la 6.8 fijate que ahora vienen seteados en el settings.gradle los repos

**Comment by AlessandroEverest** [comment]
Sou DEV Flutter, preciso ajuda urgente : 

* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.mercadopago.android.px:checkout:4.+ as no versions of com.mercadopago.android.px:checkout are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mercadopago/android/px/checkout/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/mercadopago/android/px/checkout/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/mercadopago/android/px/checkout/maven-metadata.xml
