### ISSUE TITLE
exported needs to be explicitly specified for element 

### ISSUE THREAD

**Issue by BookmanTasty** [mercadopago/px-android#2675]
Not compile 

get this error on compile 

Manifest merger failed : android:exported needs to be explicitly specified for element <activity#com.mercadopago.android.px.internal.features.checkout.CheckoutActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by guchito9** [comment]
Hi! Sorry for the inconvenience, we'll release a update soon!
