### ISSUE TITLE
Falta mapear algunos campos en PaymentMethod

### ISSUE THREAD

**Issue by fernandospr** [mercadopago/px-android#271]
Observar que a la clase [PaymentMethod](https://github.com/mercadopago/px-android/blob/master/sdk/src/main/java/com/mercadopago/model/PaymentMethod.java) le faltan campos que aparecen en la respuesta del [servicio payment_methods](https://api.mercadopago.com/v1/payment_methods?public_key=444a9ef5-8a6b-429f-abdf-587639155d88).

Estos son los campos que faltan mapear:

```
status
secure_thumbnail
thumbnail
deferred_capture
min_allowed_amount
max_allowed_amount
```

Notar además que `accreditation_time` está mapeado pero es el único que no tiene un `setter`.

Por favor, ¿los podrían agregar?

Gracias.

**Comment by mreverter** [comment]
Se agregaron los campos. En la próxima release va a estar disponible el cambio.
Consulta: ¿El setter lo necesitás por alguna razón?

**Comment by fernandospr** [comment]
@mreverter Gracias. En realidad no necesito ningún setter, pero como vi que el resto de los atributos lo tiene supuse que se habían olvidado de ese setter.

**Comment by fernandospr** [comment]
@mreverter Vi que en la versión 2.3.8 agregaron este fix, ¿esta versión ya está lista para usar en producción? Dado que en https://github.com/mercadopago/px-android/ vi que sigue diciendo que la dependencia es 2.3.5 y en http://mercadopago.github.io/px-android/ dice de usar la 2.3.6
