### ISSUE TITLE
Android 12

### ISSUE THREAD

**Issue by rodrigocanepa** [mercadopago/px-android#2734]
Android 12 requires android:exported needs to be explicitly specified for element <activity#com.mercadopago.android.px.internal.features.checkout.CheckoutActivity>, I can change the compileSdkVersion but when you try to install the release app from play store in a android 12 device, the installation fails because the android:exported

**Comment by elkarry** [comment]
+1

Please fix this

**Comment by Pulpogrammer** [comment]
Please FIXXXXXXX!!!!

**Comment by chillexperience** [comment]
Mismo error en que momento se le puede dar solución?

**Comment by chillexperience** [comment]
Cuando pueden darle solución a este problema

**Comment by chillexperience** [comment]
Este problema esta desencadenando un mal funcionamiento en el checkout de mercado pago cuando se le puede dar solución a este conflicto

**Comment by lucianoamenta** [comment]
Hay novedades para una posible fecha a la solución de este problema?

**Comment by guchito9** [comment]
Hi, we just released version 4.53.2 with support for this
