### ISSUE TITLE
Dev Flutter precisa suporte #px-android   checkout 

### ISSUE THREAD

**Issue by AlessandroEverest** [mercadopago/px-android#2735]
Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mercadopago/android/px/checkout/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/mercadopago/android/px/checkout/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/mercadopago/android/px/checkout/maven-metadata.xml
     Required by:
         project :app

**Comment by guchito9** [comment]
Please try again with version 4.53.2 and check the readme carefully as you need to add a repository to use this library.
