### ISSUE TITLE
Sdk version isn't compatilble

### ISSUE THREAD

**Issue by muneeb2218** [mercadopago/px-android#2743]
While uploading app on play store this issue occurs
![WhatsApp Image 2022-09-09 at 5 24 22 PM](https://user-images.githubusercontent.com/96496986/189356823-7be5e74d-1c77-462d-be65-2ae5e92f0918.jpeg)

**Comment by guchito9** [comment]
Yo need to upgrade to that version.

**Comment by muneeb2218** [comment]
There no update on version exists

**Comment by muneeb2218** [comment]
4.53.2 doesn't exists

**Comment by guchito9** [comment]
You are missing a repository, read the readme please.

**Comment by muneeb2218** [comment]
PX-Android 4.53.1 is the last version with a minimum API level 19.
 This is what I found on your readme and I am using same but still it throws error.

**Comment by migcoldev** [comment]
Yea @guchito9 , i have the same problem like @muneeb2218 ,  i m using the maven repo in readme, have gradle 7.5.1,  my min sdk is 21 and sdk build 32 and android studio last version, clear and rebuild and still getting/downloading com.mercadopago.android.px  4.53.1

**Comment by guchito9** [comment]
https://artifacts.mercadolibre.com/#browse/browse:android-releases:com%2Fmercadopago%2Fandroid%2Fpx%2Fcheckout%2F4.53.2

The artifact is there, you're a missing the repo in your config
