### ISSUE TITLE
Failed to resolve: com.mercadopago.android.px:checkout:4.53.2

### ISSUE THREAD

**Issue by ev-admin** [mercadopago/px-android#2744]
Hi, any help appreciated.

Im getting Failed to resolve: com.mercadopago.android.px:checkout:4.53.2.
minSdkVersion 21
targetSdkVersion 32

**Comment by guchito9** [comment]
https://artifacts.mercadolibre.com/#browse/browse:android-releases:com%2Fmercadopago%2Fandroid%2Fpx%2Fcheckout%2F4.53.2

**Comment by ev-admin** [comment]
Gracias por responder. En Android studio me tira ese error, vi que esta subida pero si especifico esa version no la encuentra. La 4.53.1 si la encuentra. Se te ocurre?

**Comment by guchito9** [comment]
Te está faltando el repositorio porque tiene que encontrarla, como es tu settings.gradle?

**Comment by grago** [comment]
Hola, me pasa lo mismo, no se encuentra la versión 4.53.2 

El repositorio está agregado:

`maven { url 'https://artifacts.mercadolibre.com/repository/android-releases/'  }`

Al intentar subir mi aplicación a Google Play utilizando la versión 4.53.1 de la librería, sale un warning indicando que ya no se aceptará esta versión a partir de Octubre, y recomienda actualizar a la versión 4.53.2, por eso es importante poder actualizarla.

Muchas gracias de antemano.

**Comment by grago** [comment]
En caso de que alguien tenga el mismo problema, el repositorio hay que agregarlo dentro de repositories {} en en el build.gradle a nivel de app.

Si no se hace de esta manera, va a descargar como última versión la 4.53.1 (que ya no se admite para subir a Google Play)

**Comment by ngonzano** [comment]
alguien llego a solucionarlo me sale errores parecidos.

Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mercadopago.android.px:checkout:4.53.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/mercadopago/android/px/checkout/4.53.2/checkout-4.53.2.pom
       - https://repo.maven.apache.org/maven2/com/mercadopago/android/px/checkout/4.53.2/checkout-4.53.2.pom
       - https://storage.googleapis.com/download.flutter.io/com/mercadopago/android/px/checkout/4.53.2/checkout-4.53.2.pom
     Required by:
         project :app

**Comment by CristoferM-A** [comment]
@ngonzano me sale un error igual que el tuyo, lograste solucionarlo??
