### ISSUE TITLE
Error al generar appbundle

### ISSUE THREAD

**Issue by mayorquin** [mercadopago/px-android#2747]
El dia de ayer me empezó a macar este error:

Execution failed for task ':app:mergeReleaseResources'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.mercadolibre.android:ui:9.+.
     Required by:
         project :app > com.mercadopago.android.px:checkout:4.53.2
         project :app > com.mercadopago.android.px:checkout:4.53.2 > com.mercadolibre.android.mlbusinesscomponents:mlbusinesscomponents:1.23.0
         project :app > com.mercadopago.android.px:checkout:4.53.2 > com.mercadolibre.android:cardform:1.16.1
      > Failed to list versions for com.mercadolibre.android:ui.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/mercadolibre/android/ui/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/mercadolibre/android/ui/maven-metadata.xml'.
               > Read timed out

Habia esta funcionando correctamente, pero ayer empezo a mandar este error.

**Comment by nelsongc** [comment]
me pasa lo mismo, hay alguna solucion?

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mercadolibre.android:ui:8.+.
     Required by:
         project :app > com.mercadopago.android.px:checkout:4.53.1
      > Failed to list versions for com.mercadolibre.android:ui.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/mercadolibre/android/ui/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/mercadolibre/android/ui/maven-metadata.xml'.
               > Read timed out
   > Could not resolve com.mercadolibre.android:carddrawer:2.+.

**Comment by nelsongc** [comment]
ya volvio a funcionar

**Comment by guchito9** [comment]
Hola, parece que fue un problema con Jcenter, que bueno que ya está solucionado!
