### ISSUE TITLE
Release 3.0.0-beta

### ISSUE THREAD

**Issue by valeserber** [mercadopago/px-android#383]
## Versión 3.0.0-beta

- Inicio de checkout con entidad "Checkout Preference".
**Modo de uso 1**: Checkout Preference creada en el cliente. El pago deberá realizarse en el servidor del integrador, utilizando su clave privada.
**Modo de uso 2**: Checkout Preference creada en el servidor del integrador. Al haber creado una preferencia con clave privada, la SDK se encarga de realizar el pago.
- Elección de checkout completo (con creación del pago) o sólo recolección de datos.
- Customización de servicios de pago: el integrador podrá definir a qué servicio y con qué información se realiza un POST que esperará como respuesta un pago.

**Comment by mreverter** [comment]
DONE
