### ISSUE TITLE
AppTheme que puede generar conflicto

### ISSUE THREAD

**Issue by fernandospr** [mercadopago/px-android#418]
La biblioteca de mercadopago tiene como dependencia:
`compile 'com.mercadopago:tracking:1.2.2'`

La biblioteca de tracking tiene estos estilos que pueden generar conflicto con los de la app que utilice la biblioteca de mercadopago:
![screen shot 2017-02-15 at 4 43 48 pm](https://cloud.githubusercontent.com/assets/4404680/22992387/5182b006-f39e-11e6-8824-ced12a84d444.png)
![screen shot 2017-02-15 at 4 43 38 pm](https://cloud.githubusercontent.com/assets/4404680/22992394/57b5fcc6-f39e-11e6-8c1f-baf6caaf0add.png)

¿Podrán renombrarlos a AppTheme.MercadoPago.xxxx por ejemplo?

**Comment by mreverter** [comment]
Resuelto en versión 2.3.7
