### ISSUE TITLE
Wording "Revisa y Confirma"

### ISSUE THREAD

**Issue by DTecheira** [mercadopago/px-android#436]
Según tengo entendido el wording debería ser "Cambiar medio de pago", @stasso podrías confirmarlo?
Gracias.

![device-2017-03-02-183007](https://cloud.githubusercontent.com/assets/1074288/23527855/4bfb5000-ff76-11e6-9443-237f1d702026.png)

**Comment by stasso** [comment]
Si, lo correcto es "Cambiar medio de pago"

@DTecheira

**Comment by mreverter** [comment]
DONE
