### ISSUE TITLE
Email is mandatory when performing basic checkout with startCheckoutActivity

### ISSUE THREAD

**Issue by euri16** [mercadopago/px-android#464]
I'm having a problem when performing a basic checkout with the function `startCheckoutActivity()`. It throws an error on runtime because the email field is mandatory, here's how I do it:

```
new MercadoPago.StartActivityBuilder()
                    .setActivity(this)
                    .setPublicKey(BuildConfig.MP_PUBLIC_KEY)
                    .setCheckoutPreferenceId(BuildConfig.MP_PREF_ID)
                    .setDecorationPreference(decorationPreference)
                    .startCheckoutActivity();
```

I can't see how I can set the email, I tried by creating a payment object and then setting the payment to the builder, the object was like this:

```
Payment payment = new Payment();
Payer payer = new Payer();
payer.setEmail(email);
payment.setPayer(payer);
```

Please let me know how I can fix that.

**Comment by mreverter** [comment]
Hi! Payer email is required, and it must be specified in the creation of the Checkout Preference.
Docs:
[https://www.mercadopago.com.ar/developers/es/api-docs/basic-checkout/checkout-preferences/](https://www.mercadopago.com.ar/developers/es/api-docs/basic-checkout/checkout-preferences/)

**Comment by euri16** [comment]
@mreverter what if I use an existing checkout preference Id and just pass it to the builder as I did in the example snippet I pasted above?

**Comment by mreverter** [comment]
@euri16 then that existing preference must have an email. Currently, if you can't have an email associated with the preference that will start the checkout, you should use another kind of solution where you handle the payment.

It's either that or creating new preferences with the payer email included for each new checkout started using the basic checkout.

**Comment by onomade** [comment]
Why I can`t that:

```
public void submit(View view) {
        new MercadoPago.StartActivityBuilder()
                .setActivity(this)
                .setPayerEmail("useremail@email.com")
                .setPublicKey("myPublicKey")
                .setCheckoutPreferenceId(FixedPreferenceId)
                .startCheckoutActivity();
    }
```

This code return "O e-mail é obrigatório"
