### ISSUE TITLE
Getting "params error" creating a payment

### ISSUE THREAD

**Issue by jajalito** [mercadopago/px-android#504]
Hello,

I'm developing an Android app with MercadoPAgo custom checkout. I'm runnind in sandbox mode, which means: I'm using my TEST credentials (Public and Private). And also I'm using the www.mercadopago.com server url with the "/examples/doPayment" URI.

But I get "params error" when I use the method MerchantServer.createPayment(....)

I'm performing the following steps:

1- Get the corresponding Bank Issuer using method mercadopago.getIssuers
2- Select the corresponding payment method, using mercadopago.getPaymentMethods
3- Generate the following cardToken and validated it:
CardToken cardToken = new CardToken("4966382331109310", 11, 19,
        "123", "APROJuan Perez", "CI-V", "12345678");
4- Obtain a token from MP:
MercadoPago mercadoPago = new MercadoPago.Builder()
        .setContext(this)
        .setPublicKey("TEST-1a0fba31-c123-4cf6-b939-db590285e11f")
        .build();

mercadoPago.createToken(cardToken, new Callback<Token>() {.....

..So far so good...

5- Then generate the payment... HERE IS WHERE I GET THE "PARAMS ERROR":

Item item = new Item("id1", 1, DUMMY_ITEM_UNIT_PRICE);
item.setUnitPrice(DUMMY_ITEM_UNIT_PRICE);
item.setCurrencyId("id1");
item.setTitle("Titulo");
item.setQuantity(1);
item.setCurrencyId("VEF");
item.setPictureUrl("http://www.domain.com.ve/LOGO V3 REDONDO VOLUMEN.gif");
item.setDescription("Esta es la descripcion");

// Set payment method id
String paymentMethodId = paymentMethod.getId();

// Set campaign id
Long campaignId = (discount != null) ? discount.getId() : null;

// Set merchant payment
MerchantPayment payment = new MerchantPayment(item, installments, cardIssuerId,
        token, paymentMethodId, /*campaignId*/(long)0 , "TEST-2846506620479202-030512-97799e44b4ec2cc642d5a47ba72d3d86__LD_LA__-240045591");

// Create payment
MerchantServer.createPayment(activity, "https://www.mercadopago.com", "/checkout/examples/doPayment", payment, new Callback<Payment>() {

    @Override
    public void success(Payment payment) {

Any clue on the reason of why I'm getting params error??

Another question....Is it mandatory to use my own server? I think I dont need it since It is an Android app. I'm not managing inventory, etc.... WHat happen if I don't want to have nothing to do between the smartphone and MP platform?

Thanks in advance!

**Comment by zehemz** [comment]
Hi there, not sure what version are you using but I can assure you that ```MerchantServer``` is now deprecated.

We have made several changes about how we process payment with 3rd party integrations on version 4.X.X. I will recommend you take a look in our new documentation.
