### ISSUE TITLE
Cannot TEST integration with Mobile APP and Backend

### ISSUE THREAD

**Issue by fgonzalez-cespi** [mercadopago/px-android#601]
I have a strange problem:

I have two tests users, the seller (test_user_99391406@testuser.com) and the buyer (test_user_73740183@testuser.com).

I succesfully generate a preference with the seller user at my backend. I send the preference ID to the mobile app that uses the MercadoPago's Android SDK.

There, I start the checkout activiy. Problem is, I have to specify one of the public keys, the Sandbox Mode One or the Production One.

Over the production one, on the seller test user credential page, appears this message "Estás logueado con un usuario de testeo". I tried using that, and I didn't worked, a message error emerged "¡Uy! Algo salio mal. Vamos a solucionarlo. Itenta mas tarde".

If I use the Sandbox Mode public key, I can succesfully complete the payment with one of the test credit card. But then, when I send the payment ID back to the server and try to get the payment with that ID, it returns nothing.

What I am doing wrong?

**Comment by luyz2000** [comment]
nothing is wrong, mercadopago on sandbox mode does generate any id that is for all platforms I use the ruby and android api and this is normal.
