### ISSUE TITLE
Chekout Basic

### ISSUE THREAD

**Issue by JavierSolis** [mercadopago/px-android#611]
Hola, estoy intentando ejecutar el ejemplo del tutorial 

> http://mercadopago.github.io/px-android/

pero me retorna la pantalla "Uy Salio algo mal - Vamos a solucionarlo intenta mas tarde"

estos son los datos que envío

la preferencia que creo en el servidor es 

```
{
  "collector_id": 231748849,
  "sponsor_id": 217176790,
  "operation_type": "regular_payment",
  "items": [
    {
      "id": "",
      "picture_url": "",
      "title": "Test",
      "description": "",
      "category_id": "",
      "currency_id": "PEN",
      "quantity": 1,
      "unit_price": 10.4
    }
  ],
  "payer": {
    "name": "",
    "surname": "",
    "email": "",
    "date_created": "",
    "phone": {
      "area_code": "",
      "number": ""
    },
    "identification": {
      "type": "",
      "number": ""
    },
    "address": {
      "street_name": "",
      "street_number": null,
      "zip_code": ""
    }
  },
  "back_urls": {
    "success": "",
    "pending": "",
    "failure": ""
  },
  "auto_return": "",
  "payment_methods": {
    "excluded_payment_methods": [
      {
        "id": ""
      }
    ],
    "excluded_payment_types": [
      {
        "id": ""
      }
    ],
    "installments": null,
    "default_payment_method_id": null,
    "default_installments": null
  },
  "client_id": "963",
  "marketplace": "NONE",
  "marketplace_fee": 0,
  "shipments": {
    "receiver_address": {
      "zip_code": "",
      "street_number": null,
      "street_name": "",
      "floor": "",
      "apartment": ""
    }
  },
  "notification_url": null,
  "external_reference": "",
  "additional_info": "",
  "expires": false,
  "expiration_date_from": null,
  "expiration_date_to": null,
  "date_created": "2017-08-03T00:49:17.302-04:00",
  "id": "231748849-e3525a05-d66f-4d64-beff-b3394646fbb8",
  "init_point": "https://www.mercadopago.com/mpe/checkout/start?pref_id=231748849-e3525a05-d66f-4d64-beff-b3394646fbb8",
  "sandbox_init_point": "https://sandbox.mercadopago.com/mpe/checkout/pay?pref_id=231748849-e3525a05-d66f-4d64-beff-b3394646fbb8"
}
```

y en el cliente android , lo llamo según el ejemplo explica:

```
new MercadoPagoCheckout.Builder()
                .setActivity(getActivity())
                .setPublicKey("PUBLIC KEY PRODUCCION")
                .setCheckoutPreference(checkoutPreference)
                .startForPayment();
```

no logro ubicar el error, ya he probado diferentes variantes, y con otras versiones, que para Peru no funcionan otros paises si , pero no obtengo el error en esta versión, cual podría ser el problema?

Agradezco cualquier luz que puedan darme u.u

![captura de pantalla 2017-08-03 a la s 00 29 30](https://user-images.githubusercontent.com/2172876/28907265-db9b2ca0-77e2-11e7-8a6e-69c9ad02a250.png)

**Comment by mreverter** [comment]
Hola! Podés ver más detalle del error obteniendo la respuesta de la SDK. Si tocás "Salir", debería responderte con data de un "MercadoPagoError" que te de más info:

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == MercadoPagoCheckout.CHECKOUT_REQUEST_CODE) {
            if (resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE) {
                Payment payment = JsonUtil.getInstance().fromJson(data.getStringExtra("payment"), Payment.class);
                //Done!
            } else if (resultCode == RESULT_CANCELED) {
                if (data != null && data.getStringExtra("mercadoPagoError") != null) {
                    MercadoPagoError error = JsonUtil.getInstance().fromJson(data.getStringExtra("mercadoPagoError"), MercadoPagoError.class);
                } else {
                    //Resolve canceled checkout
                }
            }
        }
    }

Además, veo que en la preferencia no se especifica el email, que es requerido.
Podés comentar el BODY del request de creación de preferencia para validar que sea correcto?

Saludos!
