### ISSUE TITLE
Exemplo de como adicionar atributos do item ao checkout basico.

### ISSUE THREAD

**Issue by luizraffael** [mercadopago/px-android#617]
Não encontrei um exemplo de como adicionar os atributos: Nome produto, Valor do produto. Ao checkout basico. 
`  new MercadoPagoCheckout.Builder()
                .setActivity(this)
                .setPublicKey(mPublicKey)
                .setCheckoutPreference(getCheckoutPreference())
                .setDecorationPreference(getCurrentDecorationPreference())
                .startForPayment();`

.setItem?  // Nome(Descrição) produto.
.setValue? //Preço unitário

**Comment by zehemz** [comment]
Please, reopen the issue in English. Thanks
