### ISSUE TITLE
Support for Android SDK 26

### ISSUE THREAD

**Issue by amouly** [mercadopago/px-android#624]
I've updated the Android SDK compile version to 26, and the build tools to "26.0.1".

This created errors when compiling the MP library, for example:

> Error:(36, 36) String types not allowed (at 'fontStyle' with value 'mono_regular').
> Error:(38, 40) String types not allowed (at 'fontStyle' with value 'light').

This occurs on many XML layout files.

There is any workaround to fix this? Or a new version of the SDK has to be released?

Thanks.

**Comment by bfrachia** [comment]
@amouly Did you have any luck dealing with this issue? I'm facing it right now too.

**Comment by amouly** [comment]
@bfrachia no, I could not find a solution. Thankfully my client removed the support for MercadoPago, due hight rates and lack of technical support.

**Comment by bfrachia** [comment]
Hey @amouly , just to let you know, this issue has been solved on the latest SDK update (3.7.0)
