### ISSUE TITLE
Status bar es azul aunque se aplique decoration

### ISSUE THREAD

**Issue by francofadini** [mercadopago/px-android#625]
Al aplicar DecorationPreference todo se customiza de manera correcta, pero mantienen la status bar azul. Deberia ser el color configurado por parametro pero mas oscuro.

**Comment by gorkabeguiristain** [comment]
Tienes que añadir un atributo en "colors.xml" de este modo:
<color name="colorPrimaryDark">#556B1B</color>
Y para el status bar agarra ese color.
