### ISSUE TITLE
Retrofit pierde el contexto del endpoint

### ISSUE THREAD

**Issue by LH23** [mercadopago/px-android#627]
Estoy actualizando una app que usa una versión de MercadoPago vieja, donde el endpoint establecido en `setMerchantBaseUrl` es de la forma "http://website.com/a/b/" y el método `setMerchantGetCustomerUri` es de la forma "c/d", por lo que el pedido de `MerchantService.getCustomer` es a "http://website.com/a/b/c/d".

Ahora en el sdk 3.1 con Retrofit nuevo, tal como lo mencionan en [este issue](https://github.com/square/retrofit/issues/907), el contexto del endpoint se está perdiendo y mi pedido de `MerchantService.getCustomer` queda "http://website.com/c/d", lo cual no es válido.

Quería saber si conocen algún workaround para que Retrofit tome el contexto o si pueden implementar un fix (según menciona el issue de Retrofit el arreglo seria remover el / inicial en los tags de MerchantService de `@GET("/{uri}")` a `@GET("{uri}")` ). Si quieren puedo armar un pull request.

**Comment by zehemz** [comment]
customer services fueron deprecados en v4.
