### ISSUE TITLE
Error execute example

### ISSUE THREAD

**Issue by Ingmicha** [mercadopago/px-android#685]
Hi.

i need help with this error when i execute the example code and when the app try to inflate a component this fail

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mercadopago.example/com.mercadopago.MainActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.mercadopago.customviews.MPTextView

what can i do for resolved this problem?

**Comment by zehemz** [comment]
Issue has been solved
