### ISSUE TITLE
Error:Execution failed for task ':app:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by ederpadilla** [mercadopago/px-android#691]
In a sample with  
compile 'com.android.support:appcompat-v7:26.1.0'
compile 'com.android.support:support-v4:26.1.0'
compile 'com.android.support:design:26.1.0'
and  buildToolsVersion "26.0.2"
the dependecy can´t be added, shows
"Error:(36, 36) String types not allowed (at 'fontStyle' with value 'mono_regular').'" 
<img width="1182" alt="captura de pantalla 2017-09-28 a la s 17 14 25" src="https://user-images.githubusercontent.com/14338793/30992725-eb372dfc-a470-11e7-8e9a-27c39d3928fc.png">

    compile 'com.mercadopago:sdk:3.5.3'

**Comment by zehemz** [comment]
v3 has been deprecated. Please check last updates.
