### ISSUE TITLE
Endless loading when using startForPayment

### ISSUE THREAD

**Issue by alkatena** [mercadopago/px-android#703]
I was using `startForPayment` (with a Custom Preference created in the app, using `CheckoutPreference.Builder` to generate one (like stated in [this guide](http://mercadopago.github.io/px-android/), section "Create a local instance of a Checkout Preference")), which is incorrect, as I should have used startForPaymentData for this case.

However, this generated an endless loading, with no error, making it difficult to spot the error.

Debugging, I found out that `createPayment`method of `CheckoutPresenter`, in the `onFailure` callback, the service was returning an error claiming "no pref_id" or similar, with status code 400, and so there is no handle for this situation, making an endless loading and no error.

I think that in this situation, a log should be printed or an error shown at least, in order to understand  what's wrong.

**Comment by zehemz** [comment]
Hi! we have made some improvements about v4.+ checkout preference semantic creation.
