### ISSUE TITLE
Recibir shipments en CheckoutPreference

### ISSUE THREAD

**Issue by andrestejero** [mercadopago/px-android#710]
Buenas tardes.

Estoy intentando mostrar un envío custom en mi checkout de Android. 

```
{
"shipments":
{
"mode":"custom",
"cost":350,
"free_shipping":false,
"receiver_address"{
"zip_code":"1176",
"street_number":34,
"street_name":"Aguero",
"floor":"1",
"apartment":"A"
}
}
```

Lo recibo bien en la respuesta que da "create_preference". Es mas, si entro a la url "sandbox_init_point" puedo ver que si funciona en web. 

<img width="288" alt="captura de pantalla 2017-10-23 13 29 22" src="https://user-images.githubusercontent.com/7400828/31901398-a0b018c4-b821-11e7-9f5b-fe91a4deff37.png">

```
private void startMercadoPagoCheckout(CheckoutPreference checkoutPreference) {
        new MercadoPagoCheckout.Builder()
                .setActivity(this)
                .setPublicKey("PUBLIC_KEY")
                .setCheckoutPreference(checkoutPreference)
                .startForPayment();
}
```

Por lo que puedo ver la clase CheckoutPreference no mapea "shipments". Calculo que por eso no puedo ver el costo de envio en mi checkout.
Hay alguna forma de poder pasarle "shipments" a mi checkout? 

Muchas gracias.

**Comment by zehemz** [comment]
Hola! no soportamos shippments aún.

**Comment by edgarnsr** [comment]
Buen día, estoy teniendo ese problema. @zehemz el sdk de android/ios sigue sin soportar shippments?

**Comment by cgaggino** [comment]
Hola @edgarnsr, no está soportado todavía y no lo tenemos en el roadmap a corto plazo al menos. Vamos a tener en cuenta las solicitudes de este feature y revisarlo con el equipo para un futuro. Gracias!
